name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      run: git clone https://github.com/ambikasriv/Effort-Estimation-Tool-Capstone.git

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ambikasr
        password: Asdfghjk,.

    - name: Build and push Docker image
      run: |
        docker build -t flask_app:latest .
        docker tag flask_app:latest ambikasr/flask_app:latest
        docker push ambikasr/flask_app:latest

    - name: Deploy to Docker Hub
      run: echo "Deploy step can be customized to your hosting solution"
